CREATE DATABASE IF NOT EXISTS example;
USE example;
DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255)
);
SHOW TABLES;
INSERT INTO users VALUES(NULL, 'pavel';)
SELECT * FROM users;

